apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: store
  template:
    metadata:
      labels:
        app: store
    spec:
      containers:
      - name: store
        image: nginxdemos/hello:plain-text
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: store-service
  namespace: default
spec:
  selector:
    app: store
  ports:
  - port: 80
    targetPort: 80
---
# EXPORT: Required for Gateway to see the service
apiVersion: net.gke.io/v1
kind: ServiceExport
metadata:
  name: store-service
  namespace: default
